### ISSUE TITLE
Navegación Board Materia para atrás

### ISSUE THREAD

**Issue by GuidoHenry** [uvsy-flutter-mobile/flutter-universy-mobile-client#102]
Cuando el usuario ingresa al Board de una MATERIA, en el momento que apreta la flechita del extremo superior izquierdo, la navegacion vuelva al HOME, y debería volver al LISTADO de TODAS LAS MATERIAS.

**Comment by GonzaloSaad** [comment]
El home seria mis materias?

**Comment by GuidoHenry** [comment]
ready
