### ISSUE TITLE
Mensaje por Ausencia de datos en Lista Mis Materias

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-flutter-mobile/flutter-universy-mobile-client#54]
En caso que por error, a hora de la carga de datos se registre una carrera sin materias:
En todos los lugares donde se obtenga el Listado de Materias (ej: Mis Materias), se debería informar la situación.
Ejemplo:
"Aún se encuentran registradas materias para tu carrera"
"La institución aún no ha cargado materias para tu carrera"

**Comment by GonzaloSaad** [comment]
Me gusto. Por ese lado esta bastante piola. 

PD: Cuandro agregues issues, agregale los labels, asi sabemos de que se trata! Bien ahi Cami.
