### ISSUE TITLE
Mis Materias: Diseño del Recuadro 

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-flutter-mobile/flutter-universy-mobile-client#69]
Por comentario de usuarios:
El recuadro de la materia, podria ser, mas finito con la siguiente distribución:

Color de Año | AÑO | Nombre de Materia | Candado o tilde

Una de las inquietudes fue: el numero no se distingue bien, no llama la atencion, deberia haber titulos que los diferencie, a lo que la primer idea que opinó fue:

---PRIMER AÑO---
listado de materias
---SEGUNDO AÑO---
listado de materias 
---etc---

Para que no quede asi de estructurado, se opina que con la idea de la nueva estructuración del rectángulo quedaría bien, ya que el Numero del año quedaría más explícito y no serian necesarios los títulos.

**Comment by GonzaloSaad** [comment]
Bien ahi cami por el issue! :+1: 

Tenes alguna imagen que pueda acompañar lo que decis?

**Comment by GonzaloSaad** [comment]
Se puede subir alguna imagen a esto?
