### ISSUE TITLE
Cambiar color de fondo de la información del usuario

### ISSUE THREAD

**Issue by GuidoHenry** [uvsy-flutter-mobile/flutter-universy-mobile-client#78]
El color naranjita que tiene provoca discrepancia en el resto de la app.

**Comment by GonzaloSaad** [comment]
En que parte? Tenes alguna foto para guiarnos?

**Comment by GuidoHenry** [comment]
Obvio que tengo fotos :cop_parrot:, ahi la adjunto.

**Comment by GuidoHenry** [comment]
![Screenshot_2019-08-25-13-26-35](https://user-images.githubusercontent.com/49662338/63653549-9b606480-c744-11e9-9f96-c8a7e580e1c9.png)

**Comment by GonzaloSaad** [comment]
Te parece chocante el color del perfil?
