### ISSUE TITLE
El color utlizado en el board debe ser el mismo que el del año

### ISSUE THREAD

**Issue by maxipom** [uvsy-flutter-mobile/flutter-universy-mobile-client#88]
Actualmente los colores utilizados en el board (tanto como del carrousel y del icono de correlativas) estan en naranja, pero deberian estar en el mismo color que tiene el año (Por ejemplo en este caso deberia estar todo verde)
![image](https://user-images.githubusercontent.com/7583249/64143983-e9323800-cde8-11e9-922c-fb1a12e0cf50.png)

**Comment by GuidoHenry** [comment]
Listo, se cambio al color de la materia.
