### ISSUE TITLE
Editar Perfil: Guarda Cambios pero muestra mensaje de error

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-flutter-mobile/flutter-universy-mobile-client#98]
1)Ingresar al Perfil del usuario
2)Seleccionar "Editar Perfil"
3)Cambiar Nombre (ej: si decia Camila, escribir Camilaa)
4)Seleccionar "Editar Perfil".
*Adjunto Captura de Pantalla con mensaje de error y cambio realizado.

![1](https://user-images.githubusercontent.com/38230659/64494533-90d5bd00-d264-11e9-9f43-da36cfd10e1e.jpeg)

![2](https://user-images.githubusercontent.com/38230659/64494532-90d5bd00-d264-11e9-8871-ed59937fc88e.jpeg)

![3](https://user-images.githubusercontent.com/38230659/64494534-90d5bd00-d264-11e9-9d9b-d5cd3c25fde7.jpeg)

**Comment by GuidoHenry** [comment]
Ready
